### PR TITLE
Fix mkconfig calls

### LINKED ISSUE #63: The mkconfig update in #4 needs to be ported to the other providers
I'm working on moving this to the `Util` module and will provide a patch shortly.

### PR DESCRIPTION
**Pull request by trevor-vaughan**
Fixed:
  * Moved the puppetx/augeasproviders_grub/menuentry.rb file to util.rb
    to match the module name
  * Modified all `flush` functions to call the 'global update' mkconfig
    which was added as `PuppetX::AugeasprovidersGrub::Util.mkconfig`
  * Removed EL6 from the beaker tests since the OS is no longer
    supported by the vendor and fails to run

Added:
  * Puppet 7 support
  * EL8 support

Closes #63

### CODE REVIEW

File: lib/puppetx/augeasproviders_grub/util.rb [hunk 1]
```diff
@@ -122,40 +122,52 @@ def self.munge_grubby_value(value, flavor, grubby_info)
...
-            os_name = Facter.value(:os)['name']
-          else
-            # Support for old versions of Facter
-            unless os_name
-              os_name = Facter.value(:operatingsystem)
-            end
+        paths.map do |path|
+          begin
+            File.realpath(path)
+          rescue
```
Comment (op-ct) [inline lib/puppetx/augeasproviders_grub/util.rb:154]:
```suggestion
          rescue Errno::ENOENT
```

File: lib/puppetx/augeasproviders_grub/util.rb [hunk 2]
```diff
@@ -122,40 +122,52 @@ def self.munge_grubby_value(value, flavor, grubby_info)
...
+        # The usual fact
+        (Facter.value(:os) && Facter.value(:os)['name']) ||
+          # Legacy support
+          Facter.value(:operatingsystem) ||
+          # Fallback
+          ''
+      end
+
+      # Return the location of all valid GRUB2 configurations on the system.
       # Raise an error if not found.
```
Comment (op-ct) [inline lib/puppetx/augeasproviders_grub/util.rb:139]: Doesn't raise an error if none found

File: lib/puppetx/augeasproviders_grub/util.rb [hunk 3]
```diff
@@ -122,40 +122,52 @@ def self.munge_grubby_value(value, flavor, grubby_info)
...
+      end
 
-          paths = [
-            '/etc/grub2-efi.cfg',
-            # Handle the standard EFI naming convention
-            "/boot/efi/EFI/#{os_name.downcase}/grub.cfg"
-          ] + paths
-        end
+      # Return the location of the first discovered GRUB2 configuration.
+      # Raise an error if not found.
```
Comment (op-ct) [inline lib/puppetx/augeasproviders_grub/util.rb:161]:
```suggestion
      # @raise [Puppet::Error] if no path is found
```

File: lib/puppetx/augeasproviders_grub/util.rb [hunk 4]
```diff
@@ -122,40 +122,52 @@ def self.munge_grubby_value(value, flavor, grubby_info)
...
-          if os_info
-            os_name = Facter.value(:os)['name']
-          else
-            # Support for old versions of Facter
-            unless os_name
-              os_name = Facter.value(:operatingsystem)
-            end
+        paths.map do |path|
+          begin
+            File.realpath(path)
```
Comment (op-ct) [inline lib/puppetx/augeasproviders_grub/util.rb:153]: The previous code also validated that the path was readable and not a directory.  If we wanted to keep this extra validation, we could do:

```suggestion
            real_path = File.realpath(path)
            real_path if (File.readable?(real_path) && !File.directory?(real_path))
```

**Review by raphink — APPROVED** [review]
That's quite a large change, but LGTM

**Comment by traylenator** [comment]
Testing this not having much luck, with

```puppet
kernel_parameter{'consoleblank':
  ensure => present,
  value  => '0',
}
```
Nothing much seems to happen,

I would have expected it to be visible in the following:


```
# grub2-editenv - list
saved_entry=8acfa3bfcd324a25b72ef69f6bf3caa1-4.18.0-240.1.1.el8_3.x86_64
kernelopts=root=UUID=52a70118-54f4-4c82-8316-86ae34073a0e ro console=ttyS0,115200 console=tty0 rd.auto net.ifnames=0 crashkernel=auto rhgb quiet 
```

Using 
* herculesteam-augeasproviders 2.1.3
* herculesteam-augeasproviders_base 2.0.1
* herculesteam-augeasproviders_core 2.1.2

**Comment by traylenator** [comment]
Updated augeasproviders_core to 2.6.0 since grub was > 2.4.0

Same result.

**Comment by traylenator** [comment]
Running with debug , with a parameter that was not set:

```
Notice: /Stage[main]/Main/Kernel_parameter[foo]/value: value changed ['bar'] to ['other']
Debug: Executing: '/usr/sbin/grub2-mkconfig'
Debug: /Stage[main]/Main/Kernel_parameter[foo]: The container Class[Main] will propagate my refresh event
```
So grub2-mkconfig is called.

and node reboots

```
# cat /proc/cmdline 
BOOT_IMAGE=(hd0,gpt1)/boot/vmlinuz-4.18.0-240.1.1.el8_3.x86_64 root=UUID=52a70118-54f4-4c82-8316-86ae34073a0e ro console=ttyS0,115200 console=tty0 rd.auto net.ifnames=0 crashkernel=auto rhgb quiet consoleblank=0 foo=bar
```

So this seems okay.

**Comment by traylenator** [comment]
It seems that `grub2-mkconfig` has changed such that it now works.

It used to result in a non-bootable system.

**Comment by trevor-vaughan** [comment]
@traylenator Any chance you can help pinpoint the 'fixed' version of grub? I can add code to avoid running things if we're on a broken version.

I'm honestly surprised at this, you can't do everything through the new BLS material so it seems like this would have resulted in a lot of broken systems.

**Comment by traylenator** [comment]
My guess from the changelog alone is:

```
* Mon May 20 2019 Javier Martinez Canillas <javierm@redhat.com> - 2.02-68
- blscfg: fallback to default_kernelopts if BLS option field isn't set
  Related: rhbz#1680572
```

**Comment by traylenator** [comment]
```
* Tue Dec 11 2018 Javier Martinez Canillas <javierm@redhat.com> - 2.02-64
- Make grub2-mkconfig to honour GRUB_CMDLINE_LINUX in /etc/default/grub
  Resolves: rhbz#1637875
```

**Comment by trevor-vaughan** [comment]
Thanks, that makes sense.

I don't know that I have time to consolidate the BLS detection materials into Utils right now but we can at least make this safer.

**Comment by trevor-vaughan** [comment]
It looks like the original version of the OS shipped with 2.02-66, so the 2.02-68 limit appears to be the correct one and appears to be fixed at the first minor update (by a large jump). So this should be largely a non-issue on updated systems (but the safety hook still makes sense).

**Comment by traylenator** [comment]
Glad that matches, I do have old images I could boot and test if needed.

**Comment by trevor-vaughan** [comment]
We probably should add the BLS options based off of #60 but it'll take some additional integration work to make sure it trickles down everywhere.

**Comment by trevor-vaughan** [comment]
Well, it turns out that the version matching is going to be almost impossible to make vendor neutral. So....I'm going to mark it as supporting EL 8.1+ in the metadata for now.

**Comment by trevor-vaughan** [comment]
@raphink Added a warning to the README and bumped the metadata deps. Will try to refactor to use BLS as I can.

**Comment by trevor-vaughan** [comment]
@raphink So, Travis CI is timing out for an unknown reason. I can try mucking about with the `travis.yml` but I think you either need to migrate to Travis.com or GitHub Actions.

**Comment by trevor-vaughan** [comment]
Hold off on pushing this, debugging something in EL7

**Comment by trevor-vaughan** [comment]
@traylenator Made an update to the way `flush` was calling things. This appears to correct some issues in our `fips` module tests. Can you take another poke to see if it works for you?

Currently having some issues with el8 and FIPS mode. They broke something in the stack and I'm trying to figure out what. Prior to 8.3 everything was fine.

**Comment by trevor-vaughan** [comment]
@raphink Managed to speed up the travis tests. Also, this is now working as expected.

**Comment by trevor-vaughan** [comment]
Rebased for a single commit.
